paths:
  - src
#badge: docs
#exclude: .*/test # regex
verbose: 2 # int (0-3)
skip_magic: True
skip_file_doc: True
skip_init: True
skip_class_def: False
skip_private: True
follow_links: True
#ignore_names_file: .*/test # regex
fail_under: 100
percentage_only: False
