# This workflow runs tests and reports code coverage.

# We need a workflow name to be able to schedule it from Github UI
name: TestCoverage

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The job ID has to match repo settings for PR required checks
  TestCoverage:
    runs-on: ${{ matrix.os }}

    # Run jobs for a couple of Python versions and OSes.
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.8", "3.9"]

    name: Coverage - Python ${{ matrix.python }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch depth 0 required to compare against `main`
          fetch-depth: 0

      # Load a specific version of Python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install deps
        shell: bash
        run: make github_actions

      - name: Run tests and gather coverage stats
        shell: bash
        run: make coverage

      - name: Comment with code coverage
        uses: zapatacomputing/command-pr-comment@baca4fb9246eaaee3e47f35f296764acc394fae7
        with:
          command: make github-actions-coverage-report
          template: "🚀 Code Coverage\n```%command%```"
          update-text: "🚀 Code Coverage"
