# This workflow scans changed files and reports how much is covered by docstrings.

# We need a workflow name to be able to schedule it from Github UI
name: DocstringCoverage
on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The job ID has to match repo settings for PR required checks
  TypeChecking:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          # Fetch depth 0 required to compare against `main`
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with
          python-version: ${{ matrix.python }}
          architecture: x64
      # Used to create OS-agnostic python virtual env used for other steps.
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Install deps
        shell: bash
        run: make github_actions

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: **/*.py

      - name: Comment with docstring coverage
        uses: zapatacomputing/command-pr-comment@baca4fb9246eaaee3e47f35f296764acc394fae7
        with:
          command: make docstring-cov args="${{ steps.changed-files.outputs.all_changed_files }} -o .docstring-cov"
          template: "🚀 Code Coverage\n```%command%```"
          update-text: "🚀 Code Coverage"
