# This workflow scans changed files and reports how much is covered by docstrings.

# We need a workflow name to be able to schedule it from Github UI
name: DocstringCoverage

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The job ID has to match repo settings for PR required checks
  TypeChecking:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          # Fetch depth 0 required to compare against `main`
          fetch-depth: 0



      - name: Gather coverage stats
        shell: bash
        run: |
          changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/main) HEAD | grep .py)
          if [ ! -z "$changed_files" ];
            then interrogate $(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep .py);
          fi
