# This workflow runs tests and reports code coverage.

# We need a workflow name to be able to schedule it from Github UI
name: NightlyDependencyCheck

on:
  # runs at midnight every work day
  schedule:
    - cron: '0 0 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The job ID has to match repo settings for PR required checks
  NightlyDependencyCheck:
    runs-on: macos-latest

    timeout-minutes: 25

    name: Coverage - Python 3.11 - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch depth 0 required to compare against `main`
          fetch-depth: 0

      # Note no pip cache. We want to check the installation against the
      # latest possible package versions.
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64


      # Installation method (venv/system/etc) affects Ray behavior. We're
      # installing deps to a venv to align with the most common use case.
      # Hence, we'll need to ensure the venv is always activated. More info:
      # https://stackoverflow.com/questions/74668349/how-to-activate-a-virtualenv-in-a-github-action
      - name: Install deps
        shell: bash
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          make github_actions

      - name: Run tests and gather coverage stats
        shell: bash
        run: |
          source ./venv/bin/activate
          make coverage

  style:
    runs-on: ubuntu-latest

    name: Style - Python 3-11
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch depth 0 required to compare against `main`
          fetch-depth: 0

      # Note no pip cache. We want to check the installation against the
      # latest possible package versions.
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64

      # Installation method (venv/system/etc) affects Ray behavior. We're
      # installing deps to a venv to align with the most common use case.
      # Hence, we'll need to ensure the venv is always activated. More info:
      # https://stackoverflow.com/questions/74668349/how-to-activate-a-virtualenv-in-a-github-action
      - name: Install deps
        shell: bash
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          make github_actions

      - name: Check style
        shell: bash
        run: |
          source ./venv/bin/activate
          make style

  ruff:
    runs-on: ubuntu-latest
    name: Style - Ruff
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1