# This workflow runs automatic code style checks.

# We need a workflow name to be able to schedule it from Github UI
name: style

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The job ID has to match repo settings for PR required checks
  style:
    runs-on: ubuntu-latest

    # Run jobs for a couple of Python versions.
    strategy:
      matrix:
        # Choice of Python versions to run against:
        # * 3.9: the oldest supported version
        # * 3.11: the latest officially supported version. Used in CE images.
        python: ["3.9", "3.11"]

    name: Style - Python ${{ matrix.python }}
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3

      # Load a specific version of Python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: 'pip'

      # Installation method (venv/system/etc) affects Ray behavior. We're
      # installing deps to a venv to align with the most common use case.
      # Hence, we'll need to ensure the venv is always activated. More info:
      # https://stackoverflow.com/questions/74668349/how-to-activate-a-virtualenv-in-a-github-action
      - name: Install deps
        shell: bash
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          make github_actions

      # Pyright-specific step. Temporarily separated from the regular "style" check.
      # To be merged with 'make style' when we fix all pyright errors. Until then,
      # it only prints type errors, but doesn't fail the job.
      - name: Run pyright
        shell: bash
        run: |
          source ./venv/bin/activate
          make pyright || true

      - name: Check style
        shell: bash
        run: |
          source ./venv/bin/activate
          make style

  ruff:
    runs-on: ubuntu-latest
    name: Style - Ruff
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
