# This workflow runs automatic code style checks.

# We need a workflow name to be able to schedule it from Github UI
name: style

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The job ID has to match repo settings for PR required checks
  style:
    runs-on: ubuntu-latest

    # Run jobs for a couple of Python versions.
    strategy:
      matrix:
        python: ["3.8", "3.9"]

    name: Style - Python ${{ matrix.python }}
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3

      # Load a specific version of Python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install deps
        shell: bash
        run: make github_actions

      # Leverages Makefile to check all style linters
      - name: Check style
        shell: bash
        run: |
          make clean
          make style
